project:
  type: website
  output-dir: html

website:
  title: "Shaun Nielsen"
  favicon: metaicon.png
  open-graph:
    locale: es_ES
    site-name: Shaun Nielsen
    description: Homepage of Shaun Nielsen.
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Services
        href: services.qmd
      - icon: github
        href: https://github.com/Shaunson26
  page-footer: "Shaun Nielsen ABN 123456789"
  
format:
  html:
    theme: 
      dark: cyborg
      light: sandstone
    css: styles.css

editor: source

