project:
  type: website

website:
  title: "Shaun Nielsen"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - blog.qmd
      - text: ???
        href: something.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      dark: cyborg
      light: sandstone
    # theme: 
    #   - cosmo
    #   - custom.scss
    css: styles.css

editor: source

