---
format: 
  html:
    page-layout: full
---

::: {.grid .home-info}
::: {.g-col-12 .g-col-md-6}

[H]{.large-letter}ello! I'm Shaun Nielsen.

I'm a data-driven professional with a diverse background spanning data science and engineering, biostatistics, and web development. My experience includes freelance data science and engineering consulting, performing statistical analysis and data management for public health initiatives at NSW Health, and conducting postdoctoral ecological research at the University of NSW. I leverage my analytical and technical skills to inform decision-making and solve complex problems across public health, research, and information technology.

:::

::: {.g-col-12 .g-col-md-6}
::: profile-image
:::
:::
:::

## What I do

::: {.grid .grid-list}
::: {.g-col-12 .g-col-md-6}
::: sn-list-items

- Statistical Analysis & Biostatistics  
  - Design, implementation, interpretation
  - Regression modelling, survival analysis
  - Statistical programming (R, SAS)
  - Machine learning
  - Data visualisation
  
- Data Engineering & Management  
  - Data pipeline development and maintenance
  - Database use and management (SQL)
  - Data APIs
  - Data warehousing concepts
  
- Programming & Scripting  
  - R, SAS, SQL
  - PowerShell, shell,
  - JavaScript
  
:::
:::

::: {.g-col-12 .g-col-md-6}
::: sn-list-items

- DevOps & Software Engineering:  
  - Version control (git) 
  - Unit testing
  - Continuous Integration/Continuous Deployment (CI/CD)

- System Administration and Maintenance  
  - Windows and Linux

- Frontend Web Development  
  - HTML, CSS, JavaScript
  - Node, NPM
  - Express web framework
  - Bootstrap 5

- Project Management and Tools  
  - Strategic work item management and organisation
  - Visual progress tracking and reporting
  - Effective collaboration and communication
  

:::
:::
:::


## Where I've worked

::: {.grid .grid-list}
::: {.g-col-12 .g-col-md-6}
::: sn-list-items

-   Freelance Data Science and Engineering Consultant [2023 - current]{.year-period}
    -   University of Sydney
    -   University of NSW
    -   Sydney Children's Hospital
    -   HealthStats NSW
    -   Health Protection NSW, Arbovirus disease surveillance
    -   Iberian Congress of Biological Systematics CISA
-   NSW Health, Australia [2019 - 2022]{.year-period}
    -   Public Health Response Branch - COVID-18
    -   Centre for Epidemiology and Evidence
    -   NSW Health Biostatistics Training Program

:::
:::

::: {.g-col-12 .g-col-md-6}
::: sn-list-items

-   Lancaster University, UK [2018 - 2019]{.year-period}
    -   The Lancaster Environmental Centre
-   University of NSW, Australia [2013 - 2017]{.year-period}
    -   Centre for Marine Bio-innovation
    - School of Biological, Earth and Environmental Sciences
    - School of of Biotechnology and Biomolecular Sciences

:::
:::
:::





## My education

::: {.grid .grid-list}
::: {.g-col-12 .g-col-md-6}
::: sn-list-items
-   Master of Biostatistics
    -   University of Sydney
    -   2018 - 2022
-   NSW Health Biostatistics Training Program
    -   NSW Health
    -   2018 - 2021
    
:::
:::

::: {.g-col-12 .g-col-md-6}
::: sn-list-items
-   Doctor of Philosophy (PhD) in Biological Science
    -   University of NSW
    -   2008 - 2013
-   Bachelor of Science (Marine Science)
    -   University of NSW
    -   2003 - 2007

:::
:::
:::


## Some projects I worked on

#### Health data pipeline management

Developed and maintained a Windows server cluster at NSW Health for scheduled ETL pipelines, dashboard creation and ad-hock data requests, with automated error reporting and summary e-mail notifications, and task logging for troubleshooting. I introduced version control, modularised pipeline steps, created functions in pipelines and improved documentation for future future personel. 

#### Predictive modelling for escalation in therapy of children with IBD

Used statistical learning techniques to build a prediction model for paediatric use of ‘biologics’ in inflammatory bowel disease (IBD) using blood and stool biomarkers, with researchers and clinicians at the Sydney Children’s Hospital and University of NSW (Australia). See the working prediction model as a shiny app [here](https://shaun-nielsen.shinyapps.io/inflix-predict/).


#### Data normalisation and visualisation templates for NSW Arbovirus and Mosquito Monitoring Surveillance Program

Normalised the Arbovirus survey, laboratory and notification data, and prototyped visualisations (geographic maps, bar and line charts, heatmaps), for downstream developer use in creating the “NSW Arbovirus and Mosquito Monitoring Surveillance Program Dashboard” from Environmental Health Branch (NSW Health, Australia).  The data is used in a PowerBI report [here](https://uatweb.datansw.links.com.au/insights/arbovirus).

#### Data pipeline formalisation for spatial smoothing of health indicators

Applied software engineering and development principles to generalize, formalize and package the codebase for model based, spatial smoothing pipelines of HealthStats NSW indictors within an R package framework, including the modular functions, documentation, vignettes and unit testing. See HealthStat NSW [here](https://www.healthstats.nsw.gov.au/home)

#### Biostatistics refractive eye surgery 

Biostatistical consultant - designed the Statistical Analysis Protocol for a project analysing visual outcomes, efficacy and safety of a new generation laser eye machines with researchers at the University of NSW (Australia), Shroff Eye Centre, New Delhi (India) and Johnson & Johnson Vision (Singapore). 

#### Web application exploring local climate projections and politican voting on climate policies 

Developed and deployed an MVP web application for local climate projection and politician voting analysis with researchers from the University of Sydney (Australia). Integrated and processed data from multiple data APIs, created a fast and accurate address search database, managed the server deployment and used continuous integration and continuous delivery (CI/CD) practices. See the app [here](http://dev.myclimate.com.au)

